# Generated by Django 3.1.7 on 2021-05-17 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_auto_20210517_0011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlisting',
            name='category',
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='categories',
            field=models.ManyToManyField(related_name='auctions', to='auctions.AuctionCategory'),
        ),
        migrations.AlterField(
            model_name='auctioncategory',
            name='name',
            field=models.CharField(default='no category', max_length=20, unique=True),
        ),
    ]
