# Generated by Django 3.1.7 on 2021-05-17 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0022_auto_20210517_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='auctioneer',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='auctions', to=settings.AUTH_USER_MODEL),
        ),
    ]
