# Generated by Django 3.1.7 on 2021-05-31 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0023_auto_20210517_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctioncategory',
            name='id',
        ),
        migrations.AlterField(
            model_name='auctioncategory',
            name='name',
            field=models.CharField(default='no category', max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
