# Generated by Django 3.1.7 on 2021-05-31 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0024_auto_20210531_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctioncategory',
            name='id',
            field=models.AutoField(auto_created=True, default='', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auctioncategory',
            name='name',
            field=models.CharField(default='no category', max_length=20, unique=True),
        ),
    ]
